name: Release

on:
  push:
    branches:
      - main

jobs:
  get-version:
    uses: github-actions/.github/workflows/get-version.yml@main
    
  build:
    needs: get-version
    if: ${{ needs.get-version.outputs.will-release == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: setup rust
        uses: rust-marker/marker@v0.5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          default: true 

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Trunk
        uses: mbround18/trunk-rs@v0.0.1
    
    
