name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: setup rust
        uses: rust-marker/marker@v0.5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.targets }}
    
